export const browserCoreExamples = [
  "nexa browser status",
  "nexa browser start",
  "nexa browser stop",
  "nexa browser tabs",
  "nexa browser open https://example.com",
  "nexa browser focus abcd1234",
  "nexa browser close abcd1234",
  "nexa browser screenshot",
  "nexa browser screenshot --full-page",
  "nexa browser screenshot --ref 12",
  "nexa browser snapshot",
  "nexa browser snapshot --format aria --limit 200",
  "nexa browser snapshot --efficient",
  "nexa browser snapshot --labels",
];

export const browserActionExamples = [
  "nexa browser navigate https://example.com",
  "nexa browser resize 1280 720",
  "nexa browser click 12 --double",
  'nexa browser type 23 "hello" --submit',
  "nexa browser press Enter",
  "nexa browser hover 44",
  "nexa browser drag 10 11",
  "nexa browser select 9 OptionA OptionB",
  "nexa browser upload /tmp/nexa/uploads/file.pdf",
  'nexa browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nexa browser dialog --accept",
  'nexa browser wait --text "Done"',
  "nexa browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nexa browser console --level error",
  "nexa browser pdf",
];
